name: build and test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  ubuntu-20-04:
    runs-on: ubuntu-20.04
    name: ubuntu-20.04 (mruby-${{matrix.TARGET_MRUBY}})
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        TARGET_MRUBY:
        - master
        - 3.1.0
        - 3.0.0
        - 2.1.2
        - 2.1.1
        - 2.1.0
    env:
      MRUBY_URL: "https://github.com/mruby/mruby/archive/${{matrix.TARGET_MRUBY}}.tar.gz"
      MRUBY_DIR: "mruby-${{matrix.TARGET_MRUBY}}"
      MRUBY_CONFIG: "test_config.rb"
      LZ4_URL: "https://github.com/lz4/lz4/archive/v1.9.4.tar.gz"
      MICROCO_URL: "https://github.com/dearblue/micro-co/archive/master.tar.gz"
    steps:
    - uses: actions/checkout@v3
    - name: fetch and extract mruby
      run: wget -O- $MRUBY_URL | tar xzf -
    - name: fetch and extract contribs
      run: |
        mkdir -p contrib
        rm -rf contrib/lz4 contrib/micro-co || true
        wget -O- $LZ4_URL | tar xzf - -C contrib
        mv contrib/lz4-* contrib/lz4
        wget -O- $MICROCO_URL | tar xzf - -C contrib
        mv contrib/micro-co-* contrib/micro-co
    - name: pre-clean
      run: rake -vf $MRUBY_DIR/Rakefile clean
    - name: build
      run: rake -mvf $MRUBY_DIR/Rakefile || rake -vf $MRUBY_DIR/Rakefile
    - name: test
      run: rake -vf $MRUBY_DIR/Rakefile test
